import { LESSONS } from '/lesson-data.js?v=11';
const $=id=>document.getElementById(id),safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tabs=[...document.querySelectorAll('.game-tab')],panels={roulette:$('game-roulette'),memory:$('game-memory'),who:$('game-who'),board:$('game-board')};
tabs.forEach(tab=>tab.addEventListener('click',()=>{tabs.forEach(x=>{const active=x===tab;x.classList.toggle('active',active);x.setAttribute('aria-selected',String(active))});Object.entries(panels).forEach(([key,p])=>p.hidden=key!==tab.dataset.game)}));
// Ruleta: questions are generated from the selected lesson, so the teacher can reuse it every week.
const theme=$('gameTheme'),questions=$('rouletteQuestion'),answer=$('rouletteAnswer'),meta=$('rouletteMeta'),wheel=$('bigWheel'),count=$('rouletteCount'),reveal=$('revealAnswer');
LESSONS.forEach((l,i)=>{const option=document.createElement('option');option.value=i;option.textContent=`${String(i+1).padStart(2,'0')} · ${l.title}`;theme.append(option)});
let used=[],rotation=0,spinning=false;const current=()=>LESSONS[Number(theme.value)||0];
function pool(l){const qs=(l.questions||[]);return [{q:`¿Cómo se llama la historia de hoy?`,a:l.title},{q:`¿En qué pasaje encontramos esta historia?`,a:l.reference},{q:`¿Qué enseñanza principal recordamos?`,a:l.objective},...qs.map(q=>({q,a:`Lean juntos ${l.reference} y conversen sobre la respuesta.`})),{q:'¿Cómo podemos vivir esta enseñanza esta semana?',a:l.application||l.objective},{q:'Reto: representa una parte de la historia con un gesto.',a:'¡Todos pueden participar!'}].slice(0,12)}
function resetRoulette(){used=[];answer.textContent='';answer.classList.add('hidden-answer');reveal.disabled=true;reveal.textContent='Mostrar respuesta';questions.textContent='El maestro elige el tema y pulsa “Girar pregunta”.';meta.textContent='Listos para empezar';count.textContent='0 preguntas';$('spinGame').disabled=false}
theme.addEventListener('change',resetRoulette);$('resetGame').addEventListener('click',resetRoulette);$('spinGame').addEventListener('click',()=>{if(spinning)return;const all=pool(current()),available=all.map((_,i)=>i).filter(i=>!used.includes(i));if(!available.length){questions.textContent='¡Completaron todas las preguntas! Pulsa Reiniciar para comenzar otra vez.';$('spinGame').disabled=true;return}spinning=true;$('spinGame').disabled=true;reveal.disabled=true;answer.classList.add('hidden-answer');rotation+=1080+Math.floor(Math.random()*360);wheel.style.transform=`rotate(${rotation}deg)`;questions.textContent='La ruleta está girando…';setTimeout(()=>{const i=available[Math.floor(Math.random()*available.length)],item=all[i];used.push(i);questions.textContent=item.q;answer.textContent=item.a;meta.textContent=`${current().title} · pregunta ${used.length} de ${all.length}`;count.textContent=`${used.length} preguntas`;reveal.disabled=false;$('spinGame').disabled=false;spinning=false},1100)});reveal.addEventListener('click',()=>{answer.classList.toggle('hidden-answer');reveal.textContent=answer.classList.contains('hidden-answer')?'Mostrar respuesta':'Ocultar respuesta'});
// Memoria: the teacher controls the board, children watch the large cards on screen.
const memoryIcons=[['semilla','Creación'],['noe','Noé'],['david','David'],['leon','León'],['maestra','Maestra'],['paloma','Paloma']];let memoryState=[];let open=[];let locked=false;let matches=0;let memoryTimer;
function renderMemory(){const board=$('memoryBoard');board.innerHTML=memoryState.map((card,i)=>`<button class="memory-card ${card.flipped?'flipped':''} ${card.matched?'matched':''}" data-memory="${i}" type="button" aria-label="Tarjeta ${card.flipped||card.matched?safe(card.label):'oculta'}">${card.flipped||card.matched?`<span class="memory-art avatar-art avatar-art-${card.avatar}" aria-hidden="true"></span>` :'<span>?</span>'}</button>`).join('');$('memoryScore').textContent=`${matches} / 6 parejas`}
function resetMemory(){clearTimeout(memoryTimer);memoryState=memoryIcons.flatMap(([avatar,label])=>[{avatar,label,flipped:false,matched:false},{avatar,label,flipped:false,matched:false}]).sort(()=>Math.random()-.5);open=[];locked=false;matches=0;$('memoryMessage').textContent='Encuentra las seis parejas.';renderMemory()}
$('memoryReset').addEventListener('click',resetMemory);$('memoryBoard').addEventListener('click',event=>{const button=event.target.closest('[data-memory]');if(!button||locked)return;const i=Number(button.dataset.memory),card=memoryState[i];if(card.flipped||card.matched)return;card.flipped=true;open.push(i);renderMemory();if(open.length<2)return;locked=true;const [a,b]=open;if(memoryState[a].avatar===memoryState[b].avatar){memoryState[a].matched=memoryState[b].matched=true;matches++;open=[];locked=false;$('memoryMessage').textContent=matches===6?'🏆 ¡Todas las parejas! Celebra el repaso.':`¡Pareja encontrada! Van ${matches} de 6.`;renderMemory()}else{memoryTimer=setTimeout(()=>{memoryState[a].flipped=memoryState[b].flipped=false;open=[];locked=false;$('memoryMessage').textContent='Prueben otra vez y recuerden la historia.';renderMemory()},750)}});resetMemory();
// Who am I: teacher reveals the answer after conversation.
const whoCards=[['semilla','Adán y Eva','Viví en un jardín que Dios creó y recibí una responsabilidad especial.'],['noe','Noé','Construí un arca y obedecí a Dios aunque otros no entendían.'],['leon','Daniel','Oraba con constancia y Dios me acompañó en una noche con leones.'],['maestra','Ester','Usé mi posición para pedir ayuda por mi pueblo.'],['david','David','Confié en Dios cuando enfrenté un desafío mucho más grande que yo.'],['biblia','Jesús','Tomé unos panes y peces ofrecidos con generosidad y alimenté a una multitud.'],// La paloma corresponde al bautismo de Jesús; antes ilustraba «El buen pastor»,
// y los niños veían un ave donde esperaban un pastor con su oveja.
['paloma','Juan el Bautista','Bauticé a Jesús en el río Jordán y vi al Espíritu descender como paloma.'],['maestro','Gedeón','Aprendí a obedecer a Dios con un grupo pequeño y valiente.']];let whoIndex=0;function renderWho(){const [avatar,name,clue]=whoCards[whoIndex];$('whoSymbol').className='who-symbol who-question';$('whoSymbol').textContent='?';$('whoClue').textContent=clue;$('whoAnswer').textContent=name;$('whoAnswer').classList.add('hidden-answer');$('showWho').textContent='Revelar personaje';$('whoCount').textContent=`${whoIndex+1} de ${whoCards.length}`}$('showWho').addEventListener('click',()=>{const visible=$('whoAnswer').classList.toggle('hidden-answer');$('whoSymbol').className=visible?'who-symbol who-question':'who-symbol avatar-art avatar-art-'+whoCards[whoIndex][0];$('whoSymbol').textContent=visible?'?':'';$('showWho').textContent=visible?'Revelar personaje':'Ocultar personaje'});$('nextWho').addEventListener('click',()=>{whoIndex=(whoIndex+1)%whoCards.length;renderWho()});renderWho();
$('tvMode').addEventListener('click',async()=>{document.body.classList.toggle('tv-mode');const active=document.body.classList.contains('tv-mode');$('tvMode').textContent=active?'↙ Salir de modo TV':'⛶ Activar modo TV';if(active&&!document.fullscreenElement){try{await document.documentElement.requestFullscreen()}catch{}}else if(!active&&document.fullscreenElement){try{await document.exitFullscreen()}catch{}}});
